[NGS-861] Spot Ad integration
Tapjoy/tpe_prebid_service pull request #124
Opened 2022-04-06 18:13 UTC by Rajat2809

## Context

Spot Ad DSP integration

## Related PRs

AS: 
Go PreBid: https://github.com/Tapjoy/go-prebid/pull/92
TJX: 
TPE: 

 ## How Has This Been Tested?

`make build` yields no error.

 ## Jira Link

Jira: https://tapjoy.atlassian.net/browse/NGS-861

2022-04-07 15:54 UTC, Rajat2809 commented on config/config.go
> +	v.SetDefault("adapters.spotad.endpoint", "") // Add spotAd enpoint here
Add spot ad endpoint here

2022-04-07 15:54 UTC, Rajat2809 commented on config/config.go
> +	v.SetDefault("adapters.spotad.endpoint", "") // Add spotAd enpoint here
Add spot ad endpoint here

2022-04-07 18:22 UTC, Rajat2809 commented on deploy/kubernetes/overlays/localdev/web-internal/kustomization.yaml
> +      - PBS_ADAPTERS_SPOTAD_XAPI_ENDPOINT_US_EAST="http://tpe-prebid-service-mocks.default.svc.cluster.local/spotad_givemeads"
@umutdemirel Since there is only one end point should we remove `US_EAST` from the name?

2022-04-07 18:22 UTC, Rajat2809 commented on deploy/kubernetes/overlays/localdev/web-internal/kustomization.yaml
> +      - PBS_ADAPTERS_SPOTAD_XAPI_ENDPOINT_US_EAST="http://tpe-prebid-service-mocks.default.svc.cluster.local/spotad_givemeads"
@umutdemirel Since there is only one end point should we remove `US_EAST` from the name?

2022-04-07 19:38 UTC, eric-kansas commented on deploy/kubernetes/overlays/localdev/web-internal/kustomization.yaml
> +      - PBS_ADAPTERS_SPOTAD_XAPI_ENDPOINT_US_EAST="http://tpe-prebid-service-mocks.default.svc.cluster.local/spotad_givemeads"
should be fine, but you can if you like

2022-04-07 19:50 UTC, umutdemirel commented on deploy/kubernetes/overlays/localdev/web-internal/kustomization.yaml
> +      - PBS_ADAPTERS_SPOTAD_XAPI_ENDPOINT_US_EAST="http://tpe-prebid-service-mocks.default.svc.cluster.local/spotad_givemeads"
No no, design to support multiple endpoints now, to avoid headaches later.

2022-04-07 19:50 UTC, umutdemirel commented on deploy/kubernetes/overlays/localdev/web-internal/kustomization.yaml
> +      - PBS_ADAPTERS_SPOTAD_XAPI_ENDPOINT_US_EAST="http://tpe-prebid-service-mocks.default.svc.cluster.local/spotad_givemeads"
same answer

2022-04-07 19:51 UTC, umutdemirel commented on deploy/kubernetes/overlays/localdev/web-internal/kustomization.yaml
> +      - PBS_ADAPTERS_SPOTAD_DISABLED="true"
this is just local, so you can do it now

2022-04-08 21:39 UTC, umutdemirel reviewed
LGTM but not approving till we get endpoints and all required values. also 2 simple comments

2022-04-08 21:39 UTC, umutdemirel commented on adapters/spotad/spotad.go
> +		if spotadExt.SKADNSupported {
We should always pass false for this as this is Android only, just a reminder for TJX and AS configs

2022-04-18 17:20 UTC, Rajat2809 commented on adapters/spotad/spotad.go
> +		if spotadExt.SKADNSupported {
Yes I checked TJX and AS are setting it to false as default.

2022-04-18 19:09 UTC, umutdemirel approved these changes
LGTM!

2022-04-18 21:25 UTC, mannychu requested changes

2022-04-18 21:30 UTC, umutdemirel commented on adapters/spotad/spotad.go
> +
Oh good catch, thanks @mannychu !

2022-04-18 21:31 UTC, mannychu approved these changes
looks good!

2022-04-18 22:22 UTC, merged