Feature/ngs 394/dv360 adapter
Tapjoy/tpe_prebid_service pull request #62
Opened 2021-05-26 01:10 UTC by ChillBroYo

2021-06-03 00:02 UTC, umutdemirel reviewed
Great job @ChillBroYo & @shahbaztariq , I left some comments for small issues.

The major issue here is though, we discussed [these](https://developers.google.com/display-video/ortb-spec#supported-extension-for-device-object) fields, and decided to support them. IP is truncated only when there is a privacy flag, therefore there should be a logic in the adapter to detect that and populate necessary fields. You just need to figure out in which conditions IP is truncated.

Please backtrack from [here](https://github.com/Tapjoy/tpe_prebid_service/blob/9b149324e967326dce94e75a99ae0ddbe07e0b76/privacy/scrubber.go#L105-L115) to figure it out!

2021-06-08 14:22 UTC, ChillBroYo commented on adapters/dv360/dv360.go
> +	"fill_me_in.skadnetwork": true,
removed skan

2021-06-08 14:24 UTC, ChillBroYo commented on exchange/adapter_map.go
> +			cfg.Adapters[string(openrtb_ext.BidderDV360)].XAPI.EndpointUSEast),
done

2021-06-08 14:25 UTC, ChillBroYo commented on router/router.go
> +			cfg.Adapters[string(openrtb_ext.BidderDV360)].XAPI.EndpointUSEast),
done

2021-06-08 14:26 UTC, ChillBroYo commented on static/bidder-info/dv360.yaml
> +  email: unknown@gmail.com
done

2021-06-08 14:26 UTC, ChillBroYo commented on static/bidder-info/dv360.yaml
> +      - native
done

2021-06-08 21:36 UTC, umutdemirel requested changes
Left some comments and change requests. Let's discuss.

2021-06-08 21:36 UTC, umutdemirel commented on adapters/dv360/dv360.go
> +		} else if request.Device.IP == "" && request.Device.IPv6 != dv360Ext.RawIP {
`request.Device.IPv6 != ""` would be an alternative here. At first glance, I thought there was a mistake here :)

2021-06-08 21:36 UTC, umutdemirel commented on adapters/dv360/dv360.go
> +			IFAType:     "dpid",
You may want to put a comment next to this as `Generic device platform ID` and also point to the doc `https://developers.google.com/display-video/ortb-spec#supported-extension-for-device-object`

2021-06-08 21:36 UTC, umutdemirel commented on adapters/dv360/dv360.go
> +		requestDeviceCopy.Ext, err = json.Marshal(&deviceExt)
This overwrites the device extensions (https://github.com/Tapjoy/go-prebid/blob/f34bc613b4302ec0bde6ba1705bd78657754dd16/prebid/request.go#L210-L231) with only your new extensions. You need to merge them. It's so unfortunate that it may not be as straightforward as it sounds... Let's discuss.

2021-06-08 21:36 UTC, umutdemirel commented on adapters/dv360/dv360test/exemplary/ip_truncated.json
> +            "skadn_supported": false
we should have a test case for ip_truncated = 1, where you pass a raw IP here, and one of the flags that results in ip truncation (LAT, COPPA, CCPA...).

2021-06-08 21:36 UTC, umutdemirel commented on exchange/adapter_map.go
> +			"USEAST",
you may want to get this from configs, just like other Bidders.
```
cfg.Adapters[string(openrtb_ext.BidderDV360)].XAPI.EndpointUSEast
```

2021-06-08 21:36 UTC, umutdemirel commented on router/router.go
> +			"USEAST",
Same here.

2021-06-09 19:22 UTC, umutdemirel commented
Thanks for the great effort here @ChillBroYo & @shahbaztariq! LGTM 🚀

2021-06-09 19:23 UTC, umutdemirel approved these changes
Thanks for the great effort here @ChillBroYo & @shahbaztariq! LGTM 🚀

2021-06-09 22:30 UTC, merged